# Generated by Django 6.1 on 2026-08-30 15:07

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=core.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('placement', 'Placement test'), ('quiz', 'Lesson quiz')], default='quiz', max_length=20)),
                ('level_target', models.PositiveSmallIntegerField(choices=[(1, 'Pre-Literate / Beginner'), (2, 'Emerging Reader'), (3, 'Developing Reader'), (4, 'Functionally Proficient')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=core.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('script', models.CharField(blank=True, max_length=50)),
                ('locale_code', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=core.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('level_required', models.PositiveSmallIntegerField(choices=[(1, 'Pre-Literate / Beginner'), (2, 'Emerging Reader'), (3, 'Developing Reader'), (4, 'Functionally Proficient')], default=1)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.language')),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.UUIDField(default=core.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('proficiency_level', models.PositiveSmallIntegerField(choices=[(1, 'Pre-Literate / Beginner'), (2, 'Emerging Reader'), (3, 'Developing Reader'), (4, 'Functionally Proficient')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='core.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.UUIDField(default=core.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('level_assigned', models.PositiveSmallIntegerField(choices=[(1, 'Pre-Literate / Beginner'), (2, 'Emerging Reader'), (3, 'Developing Reader'), (4, 'Functionally Proficient')])),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.assessment')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='core.learner')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=core.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('sequence_no', models.PositiveIntegerField(default=1)),
                ('content_type', models.CharField(choices=[('reading', 'Reading content'), ('writing', 'Writing exercise'), ('vocabulary', 'Vocabulary'), ('comprehension', 'Comprehension exercise'), ('practice', 'Practice activity')], max_length=20)),
                ('body', models.TextField(blank=True, help_text='Passage text / word list / instructions')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course')),
            ],
            options={
                'ordering': ['course', 'sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=core.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('prompt_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple choice'), ('truefalse', 'True / False'), ('fill_blank', 'Fill in the blank')], default='mcq', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.assessment')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=core.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=core.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.learner')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for', to='core.lesson')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=core.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('skill_area', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('vocabulary', 'Vocabulary'), ('comprehension', 'Comprehension'), ('practice', 'Practice')], max_length=20)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.topic'),
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.UUIDField(default=core.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('percent_complete', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.learner')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.lesson')),
            ],
            options={
                'unique_together': {('learner', 'lesson')},
            },
        ),
    ]
