# Generated by Django 6.1 on 2026-09-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='preferred_language',
        ),
        migrations.AddField(
            model_name='learner',
            name='learning_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_learners', to='core.language'),
        ),
    ]
