# Generated by Django 6.1 on 2026-09-06 07:51

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_learner_preferred_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple choice'), ('truefalse', 'True / False'), ('fill_blank', 'Fill in the blank'), ('writing', 'Writing response'), ('short_text', 'Short text response')], default='mcq', max_length=20),
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=core.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed')], default='started', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('level_assigned', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pre-Literate / Beginner'), (2, 'Emerging Reader'), (3, 'Developing Reader'), (4, 'Functionally Proficient')], null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.assessment')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='core.learner')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.UUIDField(default=core.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('learner_answer', models.TextField(blank=True)),
                ('correct_answer', models.TextField(blank=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.assessmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to='core.question')),
            ],
        ),
    ]
